### ISSUE TITLE
Log all messages rather than only ones a notification is played for.

### ISSUE THREAD

**Issue by Kapps** [Kapps/PoEWhisperNotifier#12]
Likely list the ones you were there for as greyed out, or some other indicator.

**Comment by RyuuOujiXS** [comment]
Either decrease emphasis on the whispers received while active, by doing something like greying out those messages or _italicizing_ them, or increase emphasis on the whispers received while idle, by doing something like highlighting or **bolding** them.

**Comment by Kapps** [comment]
Done (though no release yet).

Good point with the emphasizing. I bolded the ones received while active.
