### ISSUE TITLE
Whispers not caught in localized clients

### ISSUE THREAD

**Issue by RojinBaka** [Kapps/PoEWhisperNotifier#13]
e.g. Russian client uses "@От кого" instead of "@From"
Would be nice to make "From" keywork configurable.

**Comment by Kapps** [comment]
I'll look at this hopefully in the next week, will be busy for a bit though.
Will add the Russian one (though I have no way of testing it), and make it so if there's an unknown word following @ it just assumes it's an incoming whisper.

**Comment by Kapps** [comment]
I didn't realize you could change the language on the standard client. That definitely makes things easier. I added support for Russian and Brazilian in [v1.9](https://github.com/Kapps/PoEWhisperNotifier/releases/tag/v1.9).
