### ISSUE TITLE
Notifications sent to Chrome app but not to mobile device.

### ISSUE THREAD

**Issue by Nukosky** [Kapps/PoEWhisperNotifier#17]

**Comment by Nukosky** [comment]
[09:10 p.m.] @<EPÏC> MEGA_CheifTotem: thank you so very much
<Failed to send PushBullet notification: Error in remote server: (401) Not authorized.>

Here is the message in the log after I receive a whisper.

**Comment by Kapps** [comment]
If your Chrome Pushbullet extension is getting notifications, that means the sending part of the whisper notifier is working, so it's an issue with the Pushbullet app on your phone. 

Make sure you have the Pushbullet app installed on your phone, and are signed into it with the same account you use with the Chrome app. Also try signing out in the app, then signing back in, that fixed it for me when I had the same problem.

**Comment by Kapps** [comment]
Ah, in that case it sounds like you either have the wrong API key, or are over 500 messages in a month. Pushbullet limits you to 500 pushes in a month through third party apps in the free account now unfortunately. Is it possible you went over that limit? Did it work before?

**Comment by Nukosky** [comment]
Eh I just installed it, so I doubt its because of the limit, I will check the API key and restart on both devices, will let you know how it went.

**Comment by Kapps** [comment]
So to confirm, you have the Pushbullet extension for Chrome and you're receiving messages there? Or are you going to the Pushbullet website and seeing them in the history? Or do you mean that you can send pushes to your phone through Chrome?

**Comment by Nukosky** [comment]
Well the app works good, it even pastes the message in the text box but for some reason it doesn't send it, so for example I get a whisper in-game a sound will pop in my PC and a message will be written in the text box on Pushbullet chat to my other device, but it won't send it. I have to manually click send so my other devices gets the message.

**Comment by Kapps** [comment]
That's really weird. If you're getting a 401 Unauthorized it shouldn't be touching Pushbullet in any way. My main suggestion would still be the Api key, and signing out and back in on the app. Hopefully that works.

**Comment by Nukosky** [comment]
Just checked my mobile device and when I click SMS in the Pushbullet app it says that I need Android 4.4+, could it be the problem?

**Comment by Nukosky** [comment]
However I can still get messages sent from my PC if I do it manually.

**Comment by Kapps** [comment]
I don't think the SMS part would matter just because I think that's for the SMS feature (but could be wrong). The API key is specific to the whisper notifier app, it needs to be put in there. Your Chrome would be able to send messages, but the whisper notifier wouldn't if the API key is wrong.

**Comment by Nukosky** [comment]
It also says that I need Android 4.3+ when I click on Notifications on my mobile, that could be it right?

**Comment by Nukosky** [comment]
Let me see if it works with another device, will let you know in a while.

**Comment by Nukosky** [comment]
Yes it works, it doesn't work with my old mobile but it does with a new one with recently upgrade Android, thanks for the reply.
