### ISSUE TITLE
Notify on Party Request

### ISSUE THREAD

**Issue by DocumentRoot** [Kapps/PoEWhisperNotifier#20]
I realize that maybe this is beyond client.txt parsing, but this really missing.

When you serf poe.trade, pm to someone, wait a bit, then alt-tab to search another item...  you dont know if the guy inv you or not.

**Comment by Kapps** [comment]
Sorry, forgot to reply to this.

I don't think this is possible unfortunately. If it's not in the client.txt then it's not possible while still obeying the terms and conditions.
