### ISSUE TITLE
i am sorry.but it unwork. i donot know why

### ISSUE THREAD

**Issue by danycv** [Kapps/PoEWhisperNotifier#26]
I download the software, unzip, and then run. select the appropriate directory, but not work. is it because I use the stream client?[](url)
![22](https://cloud.githubusercontent.com/assets/27662846/25078979/cb5e765c-236a-11e7-9212-a27d845209db.jpg)

**Comment by Kapps** [comment]
Looks like you're using https://github.com/DetectiveSquirrel/PoEWhisperNotifier rather than the version from here. Does https://github.com/Kapps/PoEWhisperNotifier/releases/tag/v2.0c work?
