### ISSUE TITLE
Check-marks under settings are off.

### ISSUE THREAD

**Issue by Mygunship** [Kapps/PoEWhisperNotifier#8]
Check-marks under settings are off.
![image](https://cloud.githubusercontent.com/assets/17792780/13720303/2a20de48-e7d3-11e5-9f62-0224cd3d953a.png)

**Comment by Kapps** [comment]
Oops, thought I replied to this. I was looking at this, and it looks like it's a C# or Visual Studio bug related to high DPI support (yet occurs even on non-high DPI machines). I can't seem to get it quite perfect (tiny checkboxes on high DPI and things still being slightly off), but should be able to get it a little bit better for the next release. Unfortunately the GUI system I use is rather starting to show its age, and wasn't really designed for high DPI machines.

**Comment by Kapps** [comment]
This is finally fixed! There's a config value I can set to support proper DPI scaling on newer versions of Windows which fixes this issue.

**Comment by Mygunship** [comment]
This issue still exist after downloading 1.8
![f6a6d85e539e4fa8ad4ddce6ca3da89f](https://cloud.githubusercontent.com/assets/17792780/16989319/c8dc34b6-4e61-11e6-9161-4c8e0495e6b4.png)

**Comment by Kapps** [comment]
Okay, apparently the fix didn't seem to work for anyone besides me somehow. :P Damn. Looking into it.

**Comment by Kapps** [comment]
Hmm, can you open your PoEWhisperNotifier.exe.config file with notepad (or any other text editor; rightclick it -> Open With -> Notepad) and see if line 11 has:

````
    <appSettings>
      <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
    </appSettings>
````

The surrounding stuff should be:

````
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
    </startup>
    <appSettings>
      <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
    </appSettings>
    <userSettings>
        <PoEWhisperNotifier.Properties.Settings>
````

**Comment by Mygunship** [comment]
The config file does include those lines.

**Comment by Kapps** [comment]
Do you know what version of Windows and what resolution or Windows Scaling % you're running at?

**Comment by Mygunship** [comment]
Windows 10 Pro, 1920 x 1080, and 100%

**Comment by Kapps** [comment]
Ah, that could be it. Every computer I'm testing on uses a high DPI display. I thought the original issue only occurred on high DPI displays so assumed yours was. I'll have to do more testing at 100% DPI.

**Comment by Kapps** [comment]
This is finally fixed for next release.
